### PR TITLE
Issue #26: Extension methods

### PR DESCRIPTION
**Pull request by mgmccarthy**
PR for moving the Validator libary from a static class to extension methods #26

### CODE REVIEW

**Comment by ledbutter** [comment]
@mgmccarthy Thanks for another contribution! I think Alex's original idea (and what I would prefer) was that the extension methods would be separate and the base Validator implementation would be left alone. In other words, that these extension methods would be contained in a separate static class. As is, this would break all users of this library. Can you switch this back and then have a separate static class with the extension methods that internally use the Validator methods?

Thanks!

**Comment by mgmccarthy** [comment]
@ledbutter.. oops! Makes sense though. What I submitted will break existing API. Sounds like we want to keep the static Validator for people that have coded against this API, and include the option of using either the static Validator OR string extension methods for those that will use Validator in the future. I'll submit another PR when I have a chance.

**Comment by mgmccarthy** [comment]
@ledbutter, just added a fourth commit to Issue #26: Extension methods #44. Basically, I wrapped the calls to the static methods on Validator in extension methods on the new ValidatorExtensions class. Old API is not broken, but new users of the library can use the extension methods off of string.

**Comment by mgmccarthy** [comment]
@ledbutter, is this what you had in mind?

**Comment by mgmccarthy** [comment]
@ledbutter, I figured I'd put the ValidatorExtensions class into a separate folder under the solution. If you're fine with the class being in the root of the project, and don't mind it sharing the same namespace as the rest of the files, I'll remove it.

**Comment by mgmccarthy** [comment]
@ledbutter, let me know if you need anything else

**Comment by ledbutter** [comment]
@mgmccarthy Sorry for the delay in getting back to you, please put it back how you had it, I just misunderstood the using statement. I do want it in a separate namespace so we do indeed need the using statement where the extension methods are used.

**Comment by mgmccarthy** [comment]
@ledbutter, did you want the physical "Extensions" folder under the project root along with the adjustment in namespace, or just the namespace adjustment? The only reason I added the folder was for the physical representation of the namespace in the project.

**Comment by ledbutter** [comment]
@mgmccarthy You can pick: I just want the separate namespace for the extension methods.

**Comment by mgmccarthy** [comment]
okay, last commit was the ValidatorExtensions moved to their own namespace and the file has been moved into a folder of the same name under the project. Review and let me know if you need anything else

**Comment by ledbutter** [comment]
Looks good, thanks @mgmccarthy!

**Pull request merged**
